apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000          # Service port
      targetPort: 5000    # Container port
  type: ClusterIP        # Only accessible inside the cluster
