apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80             # Exposed port
      targetPort: 3000     # Container port
  type: LoadBalancer       # Exposes externally (outside cluster)
